#!/bin/sh

# Включаем форвардинг пакетов
echo 1 > /proc/sys/net/ipv4/ip_forward

# Сбрасываем настройки брандмауэра
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X

# Разрешаем инициированные нами подключения извне
iptables -A INPUT -i ens160 -m state --state ESTABLISHED,RELATED -j ACCEPT

# Разрешаем подключения по SSH
iptables -A INPUT -i ens160 -p tcp --dport 22 -j ACCEPT

# Разрешаем подключения к OpenVPN
iptables -A INPUT -i ens160 -p udp --dport 1207 -j ACCEPT

# Разрешает входящий трафик из tun0
iptables -A INPUT -i tun0 -j ACCEPT

# Разрешает транзитный трафик между ens160 и tun0:
iptables -A FORWARD -i ens160 -o tun0 -j ACCEPT
iptables -A FORWARD -i tun0 -o ens160 -j ACCEPT

# Запрещаем входящие извне
iptables -A INPUT -i ens160 -j DROP

# Разрешаем инициированные нами транзитные подключения извне
iptables -A FORWARD -i ens160 -o tun0 -m state --state ESTABLISHED,RELATED -j ACCEPT

# Запрещаем транзитный трафик извне
iptables -A FORWARD -i ens160 -o tun0 -j DROP

# Включаем маскарадинг для локальной сети
iptables -t nat -A POSTROUTING -o ens160 -s 10.10.10.0/24 -j MASQUERADE